spring:
  application:
     name: GitHubRepoApplication
api:    
  githup:
    url: https://api.github.com
    username:
    token:
    
server:
  port: 9090
  
springdoc:
  api-docs:
    groups:
      enabled: true
   
